### ISSUE TITLE
No Issue

### ISSUE THREAD

**Issue by Mxnority** [marks-st/MarkModeAmongUs#3]
Hey, I'm interersted in your mod and would like to introduce you to a website where you can post all your among us mods (role mods, etc.) No mod menus, Can you contact me on discord? Minority#1583

**Comment by marks-st** [comment]
Why did you make an issue then? Write a message.
Also I'm not really interested to be introduced to any site. If you want to show it on a website, feel free to do so.

**Comment by Mxnority** [comment]
It was the only way I knew how to contact you, since you didn't leave any contacts.
The website with your mod: https://amodsus.com/resources/mark-mode.51/
